# Generated by Django 3.2.13 on 2022-04-11 13:57

from django.db import migrations, models
import register.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'An account with that email already exists.'}, max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=16, unique=True, validators=[register.validators.UsernameValidator], verbose_name='username')),
                ('profile_name', models.CharField(max_length=30, verbose_name='profile_name')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='description')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='date_of_birth')),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
